{% set version = "0.19.4" %}

package:
  name: jupyterthemes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterthemes/jupyterthemes-{{ version }}.tar.gz
  sha256: 66f179a7758b6e28fea9236a6df7750d122a86008e7db3ddeded58ec951104ca

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - jupyter-theme = jupyterthemes:main
    - jt = jupyterthemes:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - jupyter_core
    - ipython >=5.4.1
    - matplotlib >=1.4.3
    - lesscpy >=0.11.2

test:
  imports:
    - jupyterthemes

  commands:
    - jupyter-theme --help
    - jt --help

about:
  home: https://github.com/dunovank/jupyter-themes
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: 'Select and install a Jupyter notebook theme'
  dev_url: https://github.com/dunovank/jupyter-themes
  doc_url: https://github.com/dunovank/jupyter-themes

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
