{% set name = "jupyterthemes" %}
{% set version = "0.18.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "7cc62193b43b835f43ae2ae183aa79c02deed0deb15e6f395ec56f6da1fefa53" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}
build:
  noarch: python
  entry_points:
    - jupyter-theme = jupyterthemes:main
    - jt = jupyterthemes:main
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - jupyter_core
    - ipython >=5.4.1
    - matplotlib >=1.4.3
    - lesscpy >=0.11.2

test:
  imports:
    - jupyterthemes

  commands:
    - jupyter-theme --help
    - jt --help

about:
  home: https://github.com/dunovank/jupyter-themes
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: 'Select and install a Jupyter notebook theme'
  dev_url: https://github.com/dunovank/jupyter-themes
  doc_url: https://github.com/dunovank/jupyter-themes

extra:
  recipe-maintainers:
    - pmlandwehr
