{% set name = "jupyterthemes" %}
{% set version = "0.19.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "7e307c76eadd3f1d7247ef727f26931b50d23b4676e3b88d1e1c1063fa8a0f0a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}
build:
  noarch: python
  entry_points:
    - jupyter-theme = jupyterthemes:main
    - jt = jupyterthemes:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - jupyter_core
    - ipython >=5.4.1
    - matplotlib >=1.4.3
    - lesscpy >=0.11.2

test:
  imports:
    - jupyterthemes

  commands:
    - jupyter-theme --help
    - jt --help

about:
  home: https://github.com/dunovank/jupyter-themes
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: 'Select and install a Jupyter notebook theme'
  dev_url: https://github.com/dunovank/jupyter-themes
  doc_url: https://github.com/dunovank/jupyter-themes

extra:
  recipe-maintainers:
    - pmlandwehr
