{% set version = "0.20.0" %}

package:
  name: jupyterthemes
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterthemes/jupyterthemes-{{ version }}.tar.gz
  sha256: 2a8ebc0c84b212ab99b9f1757fc0582a3f53930d3a75b2492d91a7c8b36ab41e

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-theme = jupyterthemes:main
    - jt = jupyterthemes:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_core
    - ipython >=5.4.1
    - matplotlib-base >=1.4.3
    - lesscpy >=0.11.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - jupyterthemes

  commands:
    - jupyter-theme --help
    - jt --help

about:
  home: https://github.com/dunovank/jupyter-themes
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT
  summary: 'Select and install a Jupyter notebook theme'
  dev_url: https://github.com/dunovank/jupyter-themes
  doc_url: https://github.com/dunovank/jupyter-themes

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
