travis:
  secure:
    BINSTAR_TOKEN: fvv6628Xuheu3OzHv27QqIKJ9nAwyTWp6T+fpLg0Ftc22CueueZkMNGdwszXVX3OE51Em4+iHqZ+6ymcb7AkiWydqS7vLCty4fpOcJz+Avs7MDQhK6sYRiezTuOe6cXsXFvD8a47GCxF3oGnZNwk0llhwoxlsSY132RfS9FOQ4+oHFzSCtA0y7t7KDOW+b33wgxdiWSStCCpPgSfpF3dgGz5o6YQVjc1ifMaHFT1ypZ26JwIY45EkmFglfFuhBycz92I1nkBASH/ol9wNTiYYqxdJZDtCm3VRFFUBLW7tHXWd5+o97G7bwSYtZERH75EAR0f9HFoPtb3CDgsomiDsDX/2dJzXKkRhGu9sLiyuJJLWHFWWU9fN15hE9TxnxZpI/AQ5ZhdUsTrGX2SdfJ2SeLZRL1CkDqukbDV27KmUm8h6xg2UHJGlABe7jLWdWKypMQRQEqq+HxG6kPVhd3nsRyitNDBPoZPTGtVIFmU61YDmBbJJdwLVK8AQOAbqT+HC4kggBt4m/beN8mP8VYlgFmj++fkf29HdxjlSFw5gQvxQgTL32m5bza+ddUeyGjtBeaW0XV3kOttbNwS1oDtqWyv1Iy6DAQqrZPbyZVf1cpgPwK7bkdbEApXNhk3HOr4GQvx0JbyxKf+TudGIZ1TaCKpGg2u80y8Je/Lgo1EuE0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
