travis:
  secure:
    BINSTAR_TOKEN: iJ9Bd/kkU4g3w+1brZndRJV/WfVMjtWu5mHtqt02DcfZbWuj1rYPpg+Tg3zTYlj8RF9+WCBzz7Mj4D5Jt5obIakL63rzxsGocFheMam7rz2mjYsJEbBhUqyxGHYtkXpPnr3s7ypResg5L5QM7bi5gUizZZdE55+yfEQO62nNHjPHNoxFCJHy8/olvJLAB5A5tCBdKhwVCclXLuYJjDsZi/gD0dWKQul7OXl5TdL3dYDehTTBgY11g+2rb/qaM2JUOtYwUYggdD9T50Pf0WI72x8KOS9675wepT6nILs/EeStqxRWA03KG9vkZtNdojFjfcE9bm1n6UlbK148e/poXh+Wiep06CytJK8HiAlO9C8c1zPkhNgKgyHRFoyF53yRR1qNDZaYTqiatC8sNTrHIJ1RzG7hzv1RojujrNPv4twnVMcwHgLC+MdYvSXh930QoU9c2eAbbEQGDHCOsRvOvtFV29VHeGzdrktyotu5Ay8LYyzk30Fg7W9mZymhpgsCsW6iaUcAyOFhO7iqqDhStQCV5IeZoHVKwBBoc5Hm7OuCy9BgxmW8+tBLaM82aDY9QtjjTqEN0oXNSwFEsr1A7Z3NEj2U6l2+lpsjgXUG+vTOWn3dAevUqiPI/XW2gbM5zH8G3AwNrdQDHRuw6yFcAOrJ94FIKGREeipGcbU8D7A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
